version: '3.8'

services:
  php:
    image: php:8.1-fpm
    volumes:
      - .:/var/www/html
    networks:
      - ecommerce_network

  nginx:
    image: nginx:alpine
    ports:
      - '8080:80'
    volumes:
      - .:/var/www/html
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    networks:
      - ecommerce_network
    depends_on:
      - php

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - ecommerce_network

  phpmyadmin:
    image: phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - '8081:80'
    networks:
      - ecommerce_network

networks:
  ecommerce_network:
    driver: bridge
